version: '3.8'
services:

  # Laravel aplikazioa
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - ile-sarea

  # Nginx (Zerbitzari web-a)
  web:
    image: nginx:alpine
    container_name: nginx-container
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker-config/nginx:/etc/nginx/conf.d
    networks:
      - ile-sarea
    depends_on:
      - app

  # MySQL Datu-basea
  db:
    image: mysql:8.0
    container_name: db-container
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ileapaindegia_db
      MYSQL_ROOT_PASSWORD: ikasle123  # Esta es la Ãºnica que importa para root
    ports:
      - "3306:3306"
    networks:
      - ile-sarea

networks:
  ile-sarea:
    driver: bridge